<a href="https://colab.research.google.com/github/ruthzu/DS/blob/main/Task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1: Custom Dataset

This dataset represents students with features like age, gender, grade, and city.

In [16]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O"],
    "Age": [20,21,22,20,19,23,21,22,20,21,23,22,20,21,22],
    "Gender": ["F","M","M","M","F","M","F","F","M","M","F","M","F","F","M"],
    "Score": [85,78,90,67,88,76,95,89,60,72,91,84,87,79,65],
    "City": ["AA","BB","CC","AA","BB","CC","AA","BB","CC","AA","BB","CC","AA","BB","CC"]
}

df = pd.DataFrame(data, index=[f"S{i}" for i in range(1,16)])
df

    Name  Age Gender  Score City
S1     A   20      F     85   AA
S2     B   21      M     78   BB
S3     C   22      M     90   CC
S4     D   20      M     67   AA
S5     E   19      F     88   BB
S6     F   23      M     76   CC
S7     G   21      F     95   AA
S8     H   22      F     89   BB
S9     I   20      M     60   CC
S10    J   21      M     72   AA
S11    K   23      F     91   BB
S12    L   22      M     84   CC
S13    M   20      F     87   AA
S14    N   21      F     79   BB
S15    O   22      M     65   CC

In [17]:
titanic = pd.read_csv("dataset-2.csv")

titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [19]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## Step 2: Data Cleaning

- Fill missing Age values with median
- Fill missing Embarked values with mode
- Drop Cabin column due to many missing values
- Remove duplicate rows

In [20]:
titanic["Age"] = titanic["Age"].fillna(titanic["Age"].median())
titanic["Embarked"] = titanic["Embarked"].fillna(titanic["Embarked"].mode()[0])

titanic = titanic.drop(columns=["Cabin"], errors="ignore")
titanic = titanic.drop_duplicates()

### Survival Rate by Gender

This shows the average survival rate for male and female passengers.

In [21]:
titanic.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

### Survival Rate by Class

This shows how passenger class affected survival.

In [22]:
titanic.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

### Average Age per Class

This calculates the average age of passengers in each class.

In [23]:
titanic.groupby("Pclass")["Age"].mean()

Pclass
1    36.812130
2    29.765380
3    25.932627
Name: Age, dtype: float64

### Survival Rate by Age Group

Passengers are grouped into age categories to analyze survival patterns.

In [24]:
titanic["AgeGroup"] = pd.cut(
    titanic["Age"],
    bins=[0, 12, 18, 60, 100],
    labels=["Child", "Teen", "Adult", "Senior"]
)

titanic.groupby("AgeGroup")["Survived"].mean()

/tmp/ipykernel_16031/1128908182.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby("AgeGroup")["Survived"].mean()

AgeGroup
Child     0.579710
Teen      0.428571
Adult     0.365753
Senior    0.227273
Name: Survived, dtype: float64

### Female Passengers Who Survived

Filter all female passengers who survived.

In [25]:
titanic[(titanic["Sex"] == "female") & (titanic["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Adult
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,Adult
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,Teen
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,C,Adult
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,C,Teen
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C,Adult
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Adult

### Children Who Survived

Filter all children (Age < 12) who survived.

In [26]:
titanic[(titanic["Age"] < 12) & (titanic["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,S,Child
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,C,Child
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,S,Child
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,S,Child
165,166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,S,Child
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,S,Child
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,S,Child
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,S,Child
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,S,Child
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,S,Child
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,S,Child
261,262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,S,Child
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,S,Child
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,S,Child
348,349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,S,Child
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,C,Child
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,S,Child
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,S,Child
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,C,Child
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,C,Child
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,S,Child
489,490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,S,Child
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,S,Child
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,S,Child
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,S,Child
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,S,Child
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,C,Child
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,C,Child
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,S,Child
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,S,Child
751,752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,S,Child
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,S,Child
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.00,0,0,364516,12.4750,S,Child
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,S,Child
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,S,Child
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,C,Child
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,C,Child
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,S,Child
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,S,Child

### First Class Passengers Survival Rate

Calculate survival probability of passengers in first class.

In [27]:
titanic[titanic["Pclass"] == 1]["Survived"].mean()

np.float64(0.6296296296296297)

## Insights

### Who was more likely to survive?
Females had a significantly higher survival rate than males.

### Did class affect survival?
Yes. First-class passengers had the highest survival rate, while third-class had the lowest.

### Were children prioritized?
Children had a relatively higher survival rate, indicating some prioritization.

### What combination had the highest survival rate?
Female passengers in first class had the highest survival rate.